### ISSUE TITLE
Ocultar “Few tickets left get yours!” Web Pycon 2017

### ISSUE THREAD

**Issue by leonartromo** [PyConColombia/website-2017#2]
Se requiere que se oculte el Botón de "Few tickets left get yours!" ya que se encuentra visible en la pagina web de PyCon Colombia 2017.

https://2017.pycon.co/

**Comment by goanpeca** [comment]
Fixed by https://github.com/PyConColombia/website-2017/commit/e3371865f40d073be380255619d9caf81c911675
